[package]
name = "rbackup"
version = "0.1.0"
authors = ["JendaKolena <jendakolena@gmail.com>"]

[dependencies]

futures = "~0.1"
failure = "0.0.1"
log = "~0.3"
env_logger = "~0.4"
futures-cpupool = "~0.1"
lazy_static = "~0.2"
text_io = "0.1.6"
time = "0.1"
config = "0.6"
rocket = "0.3.3"
rocket_codegen = "0.3.3"
tempfile = "2.2.0"
