FROM debian:buster-slim

WORKDIR /tmp/rbackup
COPY . .

RUN apt-get update && apt-get install -y curl file sudo gcc libsodium-dev clang-6.0 pkg-config make libssl-dev liblzma-dev \
 && curl -f -L https://static.rust-lang.org/rustup.sh -O \
 && /bin/bash rustup.sh --channel=nightly --date=2018-09-26 \
 && cargo build --release